src/app/referral-program-mgr/referral-program-mgr.component.html, src/app/referral-program-mgr/referral-program-mgr.component.ts
=> Add referred Users to the admin referral info card.

Caddyfile, src/app/global-vars.service.ts, src/app/right-bar-creators/right-bar-creators-leaderboard/right-bar-creators-leaderboard.component.html, src/app/right-bar-creators/right-bar-creators-leaderboard/right-bar-creators-leaderboard.component.ts, src/app/right-bar-creators/right-bar-creators.component.ts, src/app/trends-page/trends/trends.component.ts, src/lib/services/altumbase/altumbase-service.ts
Looks like I managed to make it this time )
Fixes the Top Daily Diamonded List by using altumbase api backend.
@superzordon please review and let me know if everything is ok!
=> Top Daily Diamonded Creators List Fix

src/app/referrals/referrals.component.html, src/app/referrals/referrals.component.ts, src/app/transfer-deso/transfer-deso.component.ts, src/lib/pipes/sanitize-qrcode-pipe.ts
=> display QR code for referral codes

Caddyfile
See https://diamondapp.com/nft/a0a9de78f73067e5eeeabcaefd5ba5c5a4a34f203956d618ee56fab3a5f3764b for an example post currently broken on diamondapp.com
=> Update Caddyfile to add images.deso.org

src/app/global-vars.service.ts, src/app/right-bar-creators/right-bar-creators.component.ts, src/app/trends-page/trends/trends.component.ts, src/lib/services/altumbase/altumbase-service.ts
Fixes Top Daily gainers list by replacing pulse api endpoint with altumbase api endpoint.
=> Top Daily gainers Fix

src/app/app.module.ts, src/app/theme/themes/icydark.scss
Noticed that my previous PR about icy dark theme had some conflicts. so i made a new PR.
=> icy dark theme

src/app/app.module.ts, src/app/free-deso-message/free-deso-message.component.html, src/app/free-deso-message/free-deso-message.component.ts, src/app/jumio-status/jumio-status.component.html, src/app/landing-page/landing-page.component.html, src/app/referrals/referrals.component.html, src/app/sign-up/sign-up.component.html
=> add disclaimer around referral amount

src/app/buy-deso-page/buy-deso/buy-deso.component.html, src/app/buy-deso-page/buy-deso/buy-deso.component.ts, src/app/icons/icons.module.ts, src/app/sign-up/sign-up-transfer-deso-module/sign-up-transfer-deso.component.html, src/app/sign-up/sign-up-transfer-deso-module/sign-up-transfer-deso.component.ts, src/app/sign-up/sign-up.component.html, src/app/tab-selector/tab-selector.component.html, src/app/tab-selector/tab-selector.component.ts, src/styles.scss
- Update copy on transfer option during onboarding
- Add QR code option to send DeSo during onboarding
- Add "Buy on Coinbase" option to buy DeSo component
=> Onboarding updates

src/lib/services/mention-autofill/mentionify.ts
I tested this thing a bunch, but something got wonky after merging a bunch of branches at the end. This thing probably deserves more attention but this gets it back to a decent state.
Screen grabs in various contexts and on mobile
=> fix mention menu position

Caddyfile
Same commit to https://github.com/deso-protocol/frontend/commit/b1fc377cba6a59c715fb9ac12db9553732b30ad1
=> Add support for content from Pearl node

src/app/feed/feed-create-post/feed-create-post.component.html, src/app/messages-page/messages-thread-view/messages-thread-view.component.html
here you go @superzordon 
ill add one for sending messages too.
have not updated button text to let user know they can use ctrl/cmd+enter - github does not seem to do this either. Users that know know.
=> submit post with cmd/ctrl enter

src/app/messages-page/messages-thread-view/messages-thread-view.component.html
messages already sent when enter is pressed so dont need cmd enter
=> remove cmd/ctrl+enter support on messages

Caddyfile, src/assets/i18n/en.json, src/lib/services/embed-url-parser-service/embed-url-parser-service.spec.ts, src/lib/services/embed-url-parser-service/embed-url-parser-service.ts
The following pull request contains the required changes to support direct embedding Mousai links for the frontend.
=> added Mousai embedding support to frontend

Caddyfile
replaced twing.com with twimg.com
=> Fix typo in caddyfile

src/app/app.module.ts, src/app/blog-page/blog-detail/blog-detail.component.html, src/app/feed/feed-post/feed-post.component.html, src/app/post-interaction-details/post-interaction-details.component.html, src/app/post-interaction-details/post-interaction-details.component.spec.ts, src/app/post-interaction-details/post-interaction-details.component.ts
- extract component for social interaction count
- use new component on feed-post and blog detail
=> Add social interaction count to blog detail page

src/app/create-long-post-page/create-long-post/create-long-post.component.html, src/styles.scss
=> make quill toolbar stick to top when scrolling

src/app/browse-page/browse-page.component.html, src/app/change-account-selector/change-account-selector.component.html, src/app/change-account-selector/change-account-selector.component.ts, src/app/feed/feed.component.html, src/app/messages-page/messages-page.component.html, src/app/notifications-page/notifications-list/notifications-list.component.html, src/app/page/page.component.html, src/styles.scss
**What's been done**:
1. Some small UI/UX changes (shown on the screenshots)
2. Refactored a bit `change-account-selector` component
**Screenshots**:
=> Small UI/UX improvements

src/app/change-account-selector/change-account-selector.component.html, src/styles.scss
- fix weird spacing between the header and the feed tabs.
- fix breaking "log in" text for logged out state.
=> Jackson/small UI bugs

src/app/email-subscribe-modal/email-subscribe.component.ts, src/app/settings/settings.component.html, src/app/settings/settings.component.ts, src/app/update-profile-page/update-profile/update-profile.component.ts, src/lib/helpers/date-helpers.ts
**Screenshots**:
My timezone is GMT-2, so when UTC is 16:00, for me it's 18:00.
=> adding digest send at hour local time setting to 'Settings' modal

src/app/email-subscribe-modal/email-subscribe.component.html, src/styles.scss
=> email subscribe mobile ui btn fix

src/app/global-vars.service.ts, src/app/notifications-page/notifications-list/notifications-list.component.ts
=> Adding DAO notifications

src/app/feed/feed-post-icon-row/feed-post-icon-row.component.scss
=> Fix: fixing border color for reactions summary

src/app/reactions-details/reactions-details.component.html, src/app/reactions-details/reactions-details.component.ts
**Screenshots** (after the fix):
=> Fix: fixing bug with an empty list on reactions details when there is a user without a profile

src/app/poll/poll.component.html, src/app/poll/poll.component.ts
**Screenshots** (after the fix):
=> Fix: disabling poll options for not logged in users

tsconfig.json
https://user-images.githubusercontent.com/10476834/232472144-8b06cbe1-58fa-4e16-ab0f-95d5f760639c.mov
=> Fix: Fixing wrong VIEWPORT height calculated by infinite scroller because of wrong option in tsconfig

src/app/feed/feed.component.ts
=> Chore: Get the "New" tab back

src/app/feed/feed-post-dropdown/feed-post-dropdown.component.ts
**Video**:
https://user-images.githubusercontent.com/10476834/234591421-9d6e4119-38ab-461c-8247-ff359f870b9c.mov
=> Fix: fixing Link To Post option in the dropdown

src/app/right-bar-creators/right-bar-creators.component.ts
=> Fix: Fixing default right bar selection

src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.html, src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.ts, src/app/right-bar-creators/right-bar-creators-leaderboard/right-bar-creators-leaderboard.component.html, src/app/right-bar-creators/right-bar-creators.component.ts, src/app/trends-page/trends/trends.component.html, src/app/trends-page/trends/trends.component.ts, src/app/wallet/wallet.component.html, src/app/wallet/wallet.component.ts
=> Chore: Temporarily remove open prosper

src/app/api-internal.service.ts, src/app/app.module.ts, src/app/create-long-post-page/create-long-post/create-long-post.component.html, src/app/create-long-post-page/create-long-post/create-long-post.component.scss, src/app/create-long-post-page/create-long-post/create-long-post.component.ts, src/app/create-long-post-page/drafts-table/drafts-table.component.html, src/app/create-long-post-page/drafts-table/drafts-table.component.scss, src/app/create-long-post-page/drafts-table/drafts-table.component.spec.ts, src/app/create-long-post-page/drafts-table/drafts-table.component.ts, src/app/create-long-post-page/manage-drafts-modal/manage-drafts-modal.component.html, src/app/create-long-post-page/manage-drafts-modal/manage-drafts-modal.component.scss, src/app/create-long-post-page/manage-drafts-modal/manage-drafts-modal.component.spec.ts, src/app/create-long-post-page/manage-drafts-modal/manage-drafts-modal.component.ts, src/lib/helpers/swal-helper.ts, src/styles.scss
**Video**:
https://user-images.githubusercontent.com/10476834/234638992-796ef92e-b588-4bb4-8edb-cacd538278fa.mov
**Screenshots**:
=> Feature: Introducing draft blog posts

src/app/messages-page/thread-list-item/thread-list-item.component.html, src/app/messages-page/thread-list-item/thread-list-item.component.ts
=> Feature: Introducing group chat avatars

src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.html, src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.ts
=> Feat: Adding 'View Activity' tab back pointing to the new wallet activity page

src/app/feed/feed-create-post/feed-create-post.component.ts
=> Fix: Increasing max poll options number to 20

src/app/right-bar-creators/right-bar-creators.component.html, src/app/right-bar-creators/right-bar-creators.component.ts
=> Chore: Hide earnings card

src/app/buy-deso-page/buy-deso-megaswap/buy-deso-megaswap.component.ts, src/app/buy-deso-page/buy-deso/buy-deso.component.html, src/app/buy-deso-page/buy-deso/buy-deso.component.ts, src/app/sign-up/sign-up-transfer-deso-module/sign-up-transfer-deso.component.html, src/app/sign-up/sign-up-transfer-deso-module/sign-up-transfer-deso.component.ts, src/app/tutorial/buy-deso-tutorial-page/buy-deso-tutorial/buy-deso-tutorial.component.html, src/app/tutorial/buy-deso-tutorial-page/buy-deso-tutorial/buy-deso-tutorial.component.ts
=> Chore: remove wyre widget

src/app/feed/feed-create-post/feed-create-post.component.html
**Video**:
https://github.com/diamond-app/frontend/assets/10476834/f4d7d9db-2d69-41c9-bc6f-e97839a3df25
=> Fix: Disabling post button when processing media

src/app/creator-profile-page/creator-profile-details/creator-profile-details.component.html, src/app/creator-profile-page/creator-profile-details/creator-profile-details.component.ts
=> Hide app earnings card

Caddyfile, package-lock.json, package.json, src/app/backend-api.service.ts, src/app/cashout/cashout/cashout.component.ts, src/app/creator-profile-page/creator-profile-details/creator-profile-details.component.html, src/app/creator-profile-page/creator-profile-details/creator-profile-details.component.ts, src/app/feed/feed-create-post/feed-create-post.component.html, src/app/feed/feed-post/feed-post.component.ts, src/index.diamond.html, src/index.html
This adds a check to see if a video is using Piñata IPFS service. If so it allows the video to play safely via the Video element. URL *.mypinata.cloud is already added for media (images also use this service).  Piñata  is used by NFTz. Here a post to check `3b6ba12c73bb06841f35984a9e01d1848971f2b6860e0afe059598b79c14116f`
=> Piñata video check added to play with video element

src/app/global-vars.service.ts
This reverts commit 26d870e345212a6a026d53415846b3b500c937af.
=> Revert "Update node url (#373)"
